version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: nuget
  directory: "/build"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
